FROM oracle/graalvm-ce:19.2.0.1 as graalvm

LABEL maintainer="ivangfr@yahoo.com.br"

COPY build/libs/producer-api-*-all.jar /home/app/producer-api/build/libs/producer-api.jar
WORKDIR /home/app/producer-api
RUN gu install native-image
RUN native-image --no-server -cp build/libs/producer-api.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/producer-api .
ENTRYPOINT ["./producer-api"]
