micronaut.application.name=micronaut-simple-api

# Set this value to compare with Spring Boot and Quarkus, which have a default max-threads setting of 200.
# In Micronaut, for a FIXED configuration, the default value is 2 * Number of processors available to the JVM.
micronaut.executors.io.type=fixed
micronaut.executors.io.number-of-threads=200

endpoints.health.details-visible=ANONYMOUS
endpoints.health.disk-space.enabled=true
endpoints.info.sensitive=false
endpoints.beans.sensitive=false
endpoints.env.sensitive=false
endpoints.prometheus.sensitive=false
