FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY build/libs/micronaut-book-api-*-all.jar /home/app/micronaut-book-api/build/libs/micronaut-book-api.jar
WORKDIR /home/app/micronaut-book-api

RUN native-image --no-server --no-fallback -cp build/libs/micronaut-book-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-book-api .
ENTRYPOINT ["./micronaut-book-api"]
