FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY target/micronaut-book-api-*.jar /home/app/micronaut-book-api/target/micronaut-book-api.jar
WORKDIR /home/app/micronaut-book-api

RUN native-image -cp target/micronaut-book-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-book-api .
ENTRYPOINT ["./micronaut-book-api"]
