# Set this value to compare with Spring Boot and Micronaut, which have a default max-threads setting of 200.
# In Quarkus, if not specified, the max threads is automatically sized to the greater of 8 * available processors and 200.
quarkus.thread-pool.max-threads=200

mp.messaging.outgoing.news.connector=smallrye-kafka
mp.messaging.outgoing.news.topic=quarkus.news.jvm
%native.mp.messaging.outgoing.news.topic=quarkus.news.native
mp.messaging.outgoing.news.bootstrap.servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
mp.messaging.outgoing.news.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
# disable Dev Services for Kafka (that uses Redpanda) as we are using Zookeeper and Kafka
quarkus.kafka.devservices.enabled=false