FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY target/micronaut-elasticsearch-*.jar /home/app/micronaut-elasticsearch/target/micronaut-elasticsearch.jar
WORKDIR /home/app/micronaut-elasticsearch

RUN native-image -cp target/micronaut-elasticsearch.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-elasticsearch .
ENTRYPOINT ["./micronaut-elasticsearch"]
