FROM openjdk:14-alpine
COPY build/libs/micronaut-elasticsearch-*-all.jar micronaut-elasticsearch.jar
EXPOSE 8080
CMD ["java", "-Dcom.sun.management.jmxremote", "-Xmx128m", "-jar", "micronaut-elasticsearch.jar"]
