FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY build/libs/micronaut-elasticsearch-*-all.jar /home/app/micronaut-elasticsearch/build/libs/micronaut-elasticsearch.jar
WORKDIR /home/app/micronaut-elasticsearch

RUN native-image --no-server --no-fallback -cp build/libs/micronaut-elasticsearch.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-elasticsearch .
ENTRYPOINT ["./micronaut-elasticsearch"]
