micronaut.application.name=kafka-producer

# Set this value to compare with Spring Boot and Quarkus, which have a default max-threads setting of 200.
# In Micronaut, for a FIXED configuration, the default value is 2 * Number of processors available to the JVM.
micronaut.executors.io.type=fixed
micronaut.executors.io.number-of-threads=200

micronaut.metrics.binders.kafka.enabled=true

kafka.bootstrap.servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}

app.kafka.output.topics=micronaut.news.jvm

endpoints.health.details-visible=ANONYMOUS
endpoints.health.disk-space.enabled=true
endpoints.info.sensitive=false
endpoints.beans.sensitive=false
endpoints.env.sensitive=false
endpoints.prometheus.sensitive=false
