micronaut.application.name=micronaut-elasticsearch

# Set this value to compare with Spring Boot and Quarkus, which have a default max-threads setting of 200.
# In Micronaut, for a FIXED configuration, the default value is 2 * Number of processors available to the JVM.
micronaut.executors.io.type=fixed
micronaut.executors.io.number-of-threads=200

elasticsearch.httpHosts=http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}
elasticsearch.indexes.movies=micronaut.movies.jvm

# Include empty arrays in JSON output
jackson.serializationInclusion=ALWAYS

endpoints.health.details-visible=ANONYMOUS
endpoints.health.disk-space.enabled=true
endpoints.info.sensitive=false
endpoints.beans.sensitive=false
endpoints.env.sensitive=false
endpoints.prometheus.sensitive=false
