FROM oracle/graalvm-ce:19.2.0.1 as graalvm

LABEL maintainer="ivangfr@yahoo.com.br"

COPY build/libs/consumer-api-*-all.jar /home/app/consumer-api/build/libs/consumer-api.jar
WORKDIR /home/app/consumer-api
RUN gu install native-image
RUN native-image --no-server -cp build/libs/consumer-api.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/consumer-api .
ENTRYPOINT ["./consumer-api"]
