FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim

LABEL maintainer="ivangfr@yahoo.com.br"

COPY build/libs/producer-api-*-all.jar producer-api.jar

CMD java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar producer-api.jar

EXPOSE 8080
