FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY target/producer-api-*.jar /home/app/producer-api/target/producer-api.jar
WORKDIR /home/app/producer-api

RUN native-image -cp target/producer-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/producer-api .
ENTRYPOINT ["./producer-api"]
