FROM oracle/graalvm-ce:20.0.0-java8 as graalvm
# For JDK 11
#FROM oracle/graalvm-ce:20.0.0-java11 as graalvm
RUN gu install native-image

COPY build/libs/producer-api-*-all.jar /home/app/producer-api/build/libs/producer-api.jar
WORKDIR /home/app/producer-api

RUN native-image --no-server -cp build/libs/producer-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/producer-api .
ENTRYPOINT ["./producer-api"]
