FROM oracle/graalvm-ce:20.1.0-java11 as graalvm
RUN gu install native-image

COPY build/libs/consumer-api-*-all.jar /home/app/consumer-api/build/libs/consumer-api.jar
WORKDIR /home/app/consumer-api

RUN native-image --no-server -cp build/libs/consumer-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/consumer-api .
ENTRYPOINT ["./consumer-api"]
