FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
RUN gu install native-image

COPY target/consumer-api-*.jar /home/app/consumer-api/target/consumer-api.jar
WORKDIR /home/app/consumer-api

RUN native-image -cp target/consumer-api.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/consumer-api .
ENTRYPOINT ["./consumer-api"]
