FROM openjdk:8-jre-alpine

LABEL maintainer="ivangfr@yahoo.com.br"

COPY build/libs/springboot-simple-api-*.jar springboot-simple-api.jar

CMD ["java", "-jar", "/springboot-simple-api.jar"]

EXPOSE 8080