# Set this value to compare with Spring Boot and Micronaut, which have a default max-threads setting of 200.
# In Quarkus, if not specified, the max threads is automatically sized to the greater of 8 * available processors and 200.
quarkus.thread-pool.max-threads=200

quarkus.elasticsearch.hosts=${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}
elasticsearch.indexes.movies=quarkus.movies.jvm
%native.elasticsearch.indexes.movies=quarkus.movies.native