FROM oracle/graalvm-ce:19.2.0.1 as graalvm

LABEL maintainer="ivangfr@yahoo.com.br"

COPY build/libs/micronaut-simple-api-*-all.jar /home/app/micronaut-simple-api/build/libs/micronaut-simple-api.jar
WORKDIR /home/app/micronaut-simple-api
RUN gu install native-image
RUN native-image --no-server -cp build/libs/micronaut-simple-api.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-simple-api .
ENTRYPOINT ["./micronaut-simple-api"]
